project:
  type: website
  output-dir: docs


website:
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: false
    title-block-banner: false
    theme: cosmo

author:
  - name: The PrivacyLens Team
    affiliation: UC Berkeley School of Information
    roles: [writing]
    corresponding: true

execute:
  fig-width: 12
  fig-height: 5
  fig-align: center

bibliography: references.bib

editor_options:
  chunk_output_type: console